name: PHP Lint Check

on:
  push:
    branches: [ "main", "beta" ]
  pull_request:
    branches: [ "main", "beta" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [self-hosted, ubuntu-latest]
        
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: PHP lint
      run: |
        lint_errors=$(find app -type f -name "*.php" -exec php -l {} \; 2>&1)
        echo "$lint_errors"
        if grep -q "Parse error" <<< "$lint_errors"; then
          exit 1
        fi
